version: "3"

services:
  master: 
    build: 
      context: "./master"
    scale: 3
    # ports:
    #   - 8000:8000
    environment:
      - AUX_SERVERS=aux1:3001,aux2:3002,aux3:3003
    volumes:
      - ./master:/app

  nginx:
    image: "nginx"
    depends_on:
      - master
    ports:
      - 8080:3000
    volumes:
      - ./nginx/conf.d:/etc/nginx/
  

  aux1:
    build:
      context: "./auxiliary"
    environment:
      - PORT=3001
      - ID=aux1
    ports:
      - 9001:3001
    volumes:
      - ./auxiliary:/app
      - ./data:/data
 

  aux2:
    build:
      context: "./auxiliary"
    environment:
      - PORT=3002
      - ID=aux2
    ports:
      - 9002:3002
    volumes:
      - ./auxiliary:/app
      - ./data:/data


  aux3:
    build:
      context: "./auxiliary"
    environment:
      - PORT=3003
      - ID=aux3
    ports:
      - 9003:3003
    volumes:
      - ./auxiliary:/app
      - ./data:/data

